apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURURENDQWpTZ0F3SUJBZ0lFSTB6bi9EQU5CZ2txaGtpRzl3MEJBUXNGQURCR01Rc3dDUVlEVlFRR0V3SlMKVlRFUE1BMEdBMVVFQnhNR1RXOXpZMjkzTVJNd0VRWURWUVFLRXdwV1N5QkRiMjF3WVc1NU1SRXdEd1lEVlFRRApFd2hyT0hNdGRYTmxjakFlRncweU5qQTJNVGd4TnpRMU1EZGFGdzB6TmpBMk1UZ3hOelExTURkYU1FWXhDekFKCkJnTlZCQVlUQWxKVk1ROHdEUVlEVlFRSEV3Wk5iM05qYjNjeEV6QVJCZ05WQkFvVENsWkxJRU52YlhCaGJua3gKRVRBUEJnTlZCQU1UQ0dzNGN5MTFjMlZ5TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQwpBUUVBd3VvVExxSVBEa1hFaUJ1Y3JZL1FFL2NhUXJ0SkdHZ1lGM3Nuc2ZjalNtOWgzTmZMS1lRUFgxamprazZSClMvRUZYemo4dFkvelBYSUdZSlNCQitxQ1pMKzBHdmRQS25HQzdiT2t2OGJmVWpLWVM0eDZwaEI1ZjJVUE4vSWoKbGx4T2VLNHl6UUt1d24xTFJvN1E4NGtGSktRbk9sQjYzV2ovaFZaSnlTZ2xiaEN3MDE2MER2bTRzZFFjS2tNeQplRzNORk1ERXRWQlFZQVF6UVV4WXZxOWF4V21FMW5yc2dhUjV2TTR3djdpamdscEVVZUNvbWlKeXNPNlpDckVZCkcwSldPZTVaZHdXcFdsNHVnZnVWMmhrTVY0YUg4S2FneVVEZWxLK2phVXNJNDRVdlBzOU04YStPYkkvbUJyVXEKVEVZU1JCcFV1Sm9Gc01FblJqOFMvU0Q4aVFJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBZ1F3RHdZRApWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWo4TmZ5RTJmY0lnUDRzc1lpUFFPc0tmVzYxQXdEUVlKCktvWklodmNOQVFFTEJRQURnZ0VCQUNWOUJBZ1Judm1rYjNTSkVLYVVsZENlSjJIVVVzRXEzV0NpRzJzaHNiWm8KLzIwdXdZT3ZZdUhIazZGSmt2V01McVF0dHh3T3ZwOWNpUWxDNjdTbGlmZTBYNFVzT2lOallxNUM5MUN6UzhyVgo4ejZrSEZOUlJaS2tLK2JMaEpGK1pjNTFlMS9RS1UxYTBhZ3ZpaHJpS3pPZGUybUpBU29sVnhCMWczVEM5My9oCmx0S2Q0eVhTTXdob1hQeE4wWHdReXVqSURCNnBhbGk5NnNTVjYxUitXUy9yOGhXWHNoT0toYnlFNkRnT085dTAKVFlqZGMrZ2UreGRxVDA5KzFHZ2NGTGpEOTArZjZiKzRmOUFRYWtreWpQY2tnTnZIOVFQcDhDaC9xM25MTmFjNApVTXN3YndrM2lXTlVZK3BKSGVHdndQS3dkK0tycWFld3hrY1FTWVpETGxzPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://90.156.150.75:6443
  name: k8s
contexts:
- context:
    cluster: k8s
    user: k8s
  name: default/k8s
current-context: default/k8s
kind: Config
preferences: {}
users:
- name: k8s
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: client-keystone-auth
      env:
      - name: "OS_AUTH_URL"
        value: "https://infra.mail.ru:35357/v3/"
      - name: "OS_USERNAME"
        value: "tuskonab@gmail.com"
      # - name: "OS_PASSWORD"
      #   value: "put your password here"
      - name: "OS_PROJECT_ID"
        value: "b44933f746b94079bf46f69455807133"
      - name: "OS_DOMAIN_NAME"
        value: "users"
      interactiveMode: IfAvailable
      provideClusterInfo: false