apiVersion: v1
kind: Service
metadata:
  name: my-project-service
  namespace: my-app-prod
spec:
  selector:
    app: my-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
