name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

env:
  TF_ROOT: .
  # Переменные авторизации в VK Cloud
  OS_AUTH_URL: "https://mail.ru"
  OS_PROJECT_ID: ${{ secrets.VK_CLOUD_PROJECT_ID }}
  OS_USERNAME: ${{ secrets.VK_CLOUD_USERNAME }}
  OS_PASSWORD: ${{ secrets.VK_CLOUD_PASSWORD }}
  OS_REGION_NAME: "ru-msk"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # ВСЕ ТВОИ ПЕРЕМЕННЫЕ ИЗ TFVARS (С жесткими кавычками)
  TF_VAR_project_name: "2-lab"
  TF_VAR_availability_zone: "MS1"
  TF_VAR_public_cidr: "10.0.1.0/24"
  TF_VAR_private_cidr: "10.0.2.0/24"
  TF_VAR_image_name_prefix: "web-server-base"
  TF_VAR_key_pair: "ubuntu-STD2-1-1-15GB-Co6ramyy"
  TF_VAR_flavor: "Basic-1-1-10"
  TF_VAR_db_flavor: "STD2-2-8"
  TF_VAR_my_ip: "37.19.72.245"
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }} # Пароль спрятан в секрет ради безопасности

jobs:
  terraform_validate:
    name: "terraform_validate"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - name: Script
      run: |
        terraform init
        terraform validate

  terraform_plan:
    name: "terraform_plan"
    needs: terraform_validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - name: Script
      run: |
        terraform init
        terraform plan -out=plan.tfplan -input=false
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tf-plan
        path: plan.tfplan
        retention-days: 1

  terraform_apply:
    name: "terraform_apply"
    needs: terraform_plan
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: tf-plan
        path: .
    - name: Script
      run: |
        terraform init
        terraform apply -auto-approve plan.tfplan -input=false

