name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TF_ROOT: .
  K8S_ROOT: kubernetes
  TF_VAR_my_ip: "0.0.0.0/0"
  TF_VAR_project_name: "my-project"
  OS_AUTH_URL: "https://mail.ru"
  OS_PROJECT_ID: ${{ secrets.VK_CLOUD_PROJECT_ID }}
  OS_USERNAME: ${{ secrets.VK_CLOUD_USERNAME }}
  OS_PASSWORD: ${{ secrets.VK_CLOUD_PASSWORD }}
  OS_REGION_NAME: "ru-msk"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform_validate:
    name: "terraform_validate"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Script
      run: |
        cd $TF_ROOT
        terraform init
        terraform validate

  terraform_plan:
    name: "terraform_plan"
    needs: terraform_validate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Script
      run: |
        cd $TF_ROOT
        terraform init
        terraform plan -out=plan.tfplan
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tf-plan
        path: plan.tfplan
        retention-days: 1

  terraform_apply:
    name: "terraform_apply"
    needs: terraform_plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: tf-plan
        path: .
    - name: Script
      run: |
        cd $TF_ROOT
        terraform init
        terraform apply -auto-approve plan.tfplan

  kubectl_deploy:
    name: "kubectl_deploy"
    needs: terraform_apply
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
    - name: Script
      run: |
        echo "Разворачиваем манифесты в Kubernetes..."

